const PED_CATALOG = [

  // ── FREEMODE ────────────────────────────────────────────────────────
  { model: "mp_m_freemode_01"            , name: "Freemode Homme"            , cat: "freemode"  , tier: "free"     },
  { model: "mp_f_freemode_01"            , name: "Freemode Femme"            , cat: "freemode"  , tier: "free"     },

  // ── MILITARY ────────────────────────────────────────────────────────
  { model: "s_m_y_armymech_01"           , name: "Mecanicien Armee"          , cat: "military"  , tier: "gold"     },
  { model: "s_m_m_marine_01"             , name: "Marine 1"                  , cat: "military"  , tier: "gold"     },
  { model: "s_m_m_marine_02"             , name: "Marine 2"                  , cat: "military"  , tier: "gold"     },
  { model: "s_m_y_marine_01"             , name: "Jeune Marine 1"            , cat: "military"  , tier: "gold"     },
  { model: "s_m_y_marine_02"             , name: "Jeune Marine 2"            , cat: "military"  , tier: "gold"     },
  { model: "s_m_y_marine_03"             , name: "Jeune Marine 3"            , cat: "military"  , tier: "gold"     },
  { model: "s_m_m_armoured_01"           , name: "Blinde 1"                  , cat: "military"  , tier: "gold"     },
  { model: "s_m_m_armoured_02"           , name: "Blinde 2"                  , cat: "military"  , tier: "gold"     },
  { model: "s_m_y_blackops_01"           , name: "Ops Noires 1"              , cat: "military"  , tier: "gold"     },
  { model: "s_m_y_blackops_02"           , name: "Ops Noires 2"              , cat: "military"  , tier: "gold"     },
  { model: "s_m_y_blackops_03"           , name: "Ops Noires 3"              , cat: "military"  , tier: "gold"     },
  { model: "s_m_m_chemsec_01"            , name: "Securite Chimique"         , cat: "military"  , tier: "gold"     },
  { model: "s_m_y_pilot_01"              , name: "Pilote Militaire"          , cat: "military"  , tier: "gold"     },
  { model: "u_m_y_juggernaut_01"         , name: "Juggernaut"                , cat: "military"  , tier: "gold"     },
  { model: "s_m_y_smugmech_01"           , name: "Mecanicien Hangar"         , cat: "military"  , tier: "gold"     },
  { model: "s_m_m_pilot_01"              , name: "Pilote Avion"              , cat: "military"  , tier: "gold"     },
  { model: "s_m_m_pilot_02"              , name: "Pilote Avion 2"            , cat: "military"  , tier: "gold"     },

  // ── LAW ENFORCEMENT ─────────────────────────────────────────────────
  { model: "s_m_y_cop_01"                , name: "Policier LSPD"             , cat: "law"       , tier: "gold"     },
  { model: "s_f_y_cop_01"                , name: "Policiere LSPD"            , cat: "law"       , tier: "gold"     },
  { model: "s_m_y_hwaycop_01"            , name: "Policier Autoroute"        , cat: "law"       , tier: "gold"     },
  { model: "s_m_y_sheriff_01"            , name: "Sheriff"                   , cat: "law"       , tier: "gold"     },
  { model: "s_f_y_sheriff_01"            , name: "Sheriff Femme"             , cat: "law"       , tier: "gold"     },
  { model: "s_m_y_ranger_01"             , name: "Ranger"                    , cat: "law"       , tier: "gold"     },
  { model: "s_f_y_ranger_01"             , name: "Ranger Femme"              , cat: "law"       , tier: "gold"     },
  { model: "s_m_y_swat_01"               , name: "SWAT"                      , cat: "law"       , tier: "gold"     },
  { model: "s_m_m_snowcop_01"            , name: "Policier Neige"            , cat: "law"       , tier: "gold"     },
  { model: "s_m_y_uscg_01"               , name: "Garde-Cote"                , cat: "law"       , tier: "gold"     },
  { model: "s_m_m_fibsec_01"             , name: "Securite FIB"              , cat: "law"       , tier: "gold"     },
  { model: "s_m_m_ciasec_01"             , name: "Securite CIA"              , cat: "law"       , tier: "gold"     },
  { model: "s_m_m_security_01"           , name: "Agent Securite"            , cat: "law"       , tier: "gold"     },
  { model: "s_m_m_bouncer_01"            , name: "Videur 1"                  , cat: "law"       , tier: "gold"     },
  { model: "s_m_m_bouncer_02"            , name: "Videur 2"                  , cat: "law"       , tier: "gold"     },
  { model: "s_m_m_prisguard_01"          , name: "Gardien Prison"            , cat: "law"       , tier: "gold"     },
  { model: "s_m_y_prison_01"             , name: "Prisonnier"                , cat: "law"       , tier: "gold"     },
  { model: "s_m_y_prismuscl_01"          , name: "Prisonnier Muscle"         , cat: "law"       , tier: "gold"     },
  { model: "u_m_m_fibarchitect"          , name: "Architecte FIB"            , cat: "law"       , tier: "gold"     },
  { model: "u_m_y_babyd"                 , name: "Baby D"                    , cat: "law"       , tier: "gold"     },
  { model: "u_m_y_prisoner_01"           , name: "Prisonnier Unique"         , cat: "law"       , tier: "gold"     },
  { model: "u_f_y_corpse_01"             , name: "Corps Femme"               , cat: "law"       , tier: "gold"     },

  // ── GANG ────────────────────────────────────────────────────────────
  { model: "g_m_y_famca_01"              , name: "Families Homme 1"          , cat: "gang"      , tier: "gold"     },
  { model: "g_m_y_famdnf_01"             , name: "Families DNF"              , cat: "gang"      , tier: "gold"     },
  { model: "g_m_y_famfor_01"             , name: "Families Forum"            , cat: "gang"      , tier: "gold"     },
  { model: "g_f_y_families_01"           , name: "Families Femme"            , cat: "gang"      , tier: "gold"     },
  { model: "g_m_y_ballasout_01"          , name: "Ballas 1"                  , cat: "gang"      , tier: "gold"     },
  { model: "g_m_y_ballaeast_01"          , name: "Ballas East"               , cat: "gang"      , tier: "gold"     },
  { model: "g_m_y_ballaorig_01"          , name: "Ballas Original"           , cat: "gang"      , tier: "gold"     },
  { model: "g_f_y_ballas_01"             , name: "Ballas Femme"              , cat: "gang"      , tier: "gold"     },
  { model: "g_m_y_pologoon_01"           , name: "Vagos Polo 1"              , cat: "gang"      , tier: "gold"     },
  { model: "g_m_y_pologoon_02"           , name: "Vagos Polo 2"              , cat: "gang"      , tier: "gold"     },
  { model: "g_m_y_salvaboss_01"          , name: "Salvadors Boss"            , cat: "gang"      , tier: "gold"     },
  { model: "g_m_y_salvagoon_01"          , name: "Salvadors 1"               , cat: "gang"      , tier: "gold"     },
  { model: "g_m_y_salvagoon_02"          , name: "Salvadors 2"               , cat: "gang"      , tier: "gold"     },
  { model: "g_m_y_salvagoon_03"          , name: "Salvadors 3"               , cat: "gang"      , tier: "gold"     },
  { model: "g_m_y_lost_01"               , name: "Lost MC 1"                 , cat: "gang"      , tier: "gold"     },
  { model: "g_m_y_lost_02"               , name: "Lost MC 2"                 , cat: "gang"      , tier: "gold"     },
  { model: "g_m_y_lost_03"               , name: "Lost MC 3"                 , cat: "gang"      , tier: "gold"     },
  { model: "g_f_y_lost_01"               , name: "Lost MC Femme"             , cat: "gang"      , tier: "gold"     },
  { model: "g_m_y_mexgoon_01"            , name: "Mexicain 1"                , cat: "gang"      , tier: "gold"     },
  { model: "g_m_y_mexgoon_02"            , name: "Mexicain 2"                , cat: "gang"      , tier: "gold"     },
  { model: "g_m_y_mexgoon_03"            , name: "Mexicain 3"                , cat: "gang"      , tier: "gold"     },
  { model: "g_m_y_mexgang_01"            , name: "Gang Mexicain"             , cat: "gang"      , tier: "gold"     },
  { model: "g_m_y_armgoon_01"            , name: "Armenien 1"                , cat: "gang"      , tier: "gold"     },
  { model: "g_m_y_armgoon_02"            , name: "Armenien 2"                , cat: "gang"      , tier: "gold"     },
  { model: "g_m_m_armboss_01"            , name: "Boss Armenien"             , cat: "gang"      , tier: "gold"     },
  { model: "g_m_m_armlieut_01"           , name: "Lieutenant Armenien"       , cat: "gang"      , tier: "gold"     },
  { model: "g_m_y_korean_01"             , name: "Coreen 1"                  , cat: "gang"      , tier: "gold"     },
  { model: "g_m_y_korean_02"             , name: "Coreen 2"                  , cat: "gang"      , tier: "gold"     },
  { model: "g_m_y_koreboss_01"           , name: "Boss Coreen"               , cat: "gang"      , tier: "gold"     },
  { model: "g_m_m_chiboss_01"            , name: "Boss Chinois"              , cat: "gang"      , tier: "gold"     },
  { model: "g_m_m_chigoon_01"            , name: "Chinois 1"                 , cat: "gang"      , tier: "gold"     },
  { model: "g_m_m_chigoon_02"            , name: "Chinois 2"                 , cat: "gang"      , tier: "gold"     },
  { model: "g_m_m_chemwork_01"           , name: "Labo Chimique"             , cat: "gang"      , tier: "gold"     },
  { model: "g_m_m_mexboss_01"            , name: "Boss Mexicain 1"           , cat: "gang"      , tier: "gold"     },
  { model: "g_m_m_mexboss_02"            , name: "Boss Mexicain 2"           , cat: "gang"      , tier: "gold"     },
  { model: "g_m_y_strpunk_01"            , name: "Punk de Rue 1"             , cat: "gang"      , tier: "gold"     },
  { model: "g_m_y_strpunk_02"            , name: "Punk de Rue 2"             , cat: "gang"      , tier: "gold"     },
  { model: "g_m_importexport_01"         , name: "Import/Export"             , cat: "gang"      , tier: "gold"     },
  { model: "g_m_m_korboss_01"            , name: "Boss Coreen 2"             , cat: "gang"      , tier: "gold"     },
  { model: "mp_m_exarmy_01"              , name: "Ex-Militaire"              , cat: "gang"      , tier: "gold"     },
  { model: "g_m_y_azteca_01"             , name: "Azteca"                    , cat: "gang"      , tier: "gold"     },

  // ── STREET / AMBIENT ────────────────────────────────────────────────
  { model: "a_m_y_hipster_01"            , name: "Hipster 1"                 , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_hipster_02"            , name: "Hipster 2"                 , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_hipster_03"            , name: "Hipster 3"                 , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_skater_01"             , name: "Skater 1"                  , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_skater_02"             , name: "Skater 2"                  , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_beachvesp_01"          , name: "Plage Venice 1"            , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_beachvesp_02"          , name: "Plage Venice 2"            , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_beach_01"              , name: "Plage Homme 1"             , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_beach_02"              , name: "Plage Homme 2"             , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_beach_03"              , name: "Plage Homme 3"             , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_beach_04"              , name: "Plage Homme 4"             , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_bevhills_01"           , name: "Beverly Hills 1"           , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_bevhills_02"           , name: "Beverly Hills 2"           , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_breakdance_01"         , name: "Breakdanceur"              , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_busicas_01"            , name: "Casual Business"           , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_cyclist_01"            , name: "Cycliste"                  , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_dhill_01"              , name: "Downhill"                  , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_downtown_01"           , name: "Downtown 1"                , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_eastsa_01"             , name: "East SA 1"                 , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_eastsa_02"             , name: "East SA 2"                 , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_epsilon_01"            , name: "Epsilon 1"                 , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_epsilon_02"            , name: "Epsilon 2"                 , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_gay_01"                , name: "Gay 1"                     , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_gay_02"                , name: "Gay 2"                     , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_genstreet_01"          , name: "Rue Generique 1"           , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_genstreet_02"          , name: "Rue Generique 2"           , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_golfer_01"             , name: "Golfeur"                   , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_hasjew_01"             , name: "Juif Hassidique"           , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_hiker_01"              , name: "Randonneur"                , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_indian_01"             , name: "Indien"                    , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_jetski_01"             , name: "Jet Ski"                   , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_juggalo_01"            , name: "Juggalo"                   , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_ktown_01"              , name: "Koreatown 1"               , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_ktown_02"              , name: "Koreatown 2"               , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_latino_01"             , name: "Latino"                    , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_methhead_01"           , name: "Toxicomane"                , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_mexthug_01"            , name: "Voyou Mexicain"            , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_motox_01"              , name: "Motocross 1"               , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_motox_02"              , name: "Motocross 2"               , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_musclbeac_01"          , name: "Muscle Beach 1"            , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_musclbeac_02"          , name: "Muscle Beach 2"            , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_polynesian_01"         , name: "Polynesien"                , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_roadcyc_01"            , name: "Cycliste Route"            , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_runner_01"             , name: "Jogger 1"                  , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_runner_02"             , name: "Jogger 2"                  , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_salton_01"             , name: "Salton Sea 1"              , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_skidrow_01"            , name: "Skid Row"                  , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_socenlat_01"           , name: "South Central Latino"      , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_soucent_01"            , name: "South Central 1"           , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_soucent_02"            , name: "South Central 2"           , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_soucent_03"            , name: "South Central 3"           , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_soucent_04"            , name: "South Central 4"           , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_stbla_01"              , name: "Noir Rue 1"                , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_stbla_02"              , name: "Noir Rue 2"                , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_stwhi_01"              , name: "Blanc Rue 1"               , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_stwhi_02"              , name: "Blanc Rue 2"               , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_sunbathe_01"           , name: "Bain Soleil"               , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_surfer_01"             , name: "Surfeur"                   , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_tattoo_01"             , name: "Tatoue"                    , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_tennis_01"             , name: "Joueur Tennis"             , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_vinewood_01"           , name: "Vinewood 1"                , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_vinewood_02"           , name: "Vinewood 2"                , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_vinewood_03"           , name: "Vinewood 3"                , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_vinewood_04"           , name: "Vinewood 4"                , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_yoga_01"               , name: "Yoga Homme"                , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_clubcust_01"           , name: "Client Club 1"             , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_clubcust_02"           , name: "Client Club 2"             , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_clubcust_03"           , name: "Client Club 3"             , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_clubcust_04"           , name: "Client Club 4"             , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_hipster_01"            , name: "Hipster Femme 1"           , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_hipster_02"            , name: "Hipster Femme 2"           , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_hipster_03"            , name: "Hipster Femme 3"           , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_hipster_04"            , name: "Hipster Femme 4"           , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_beach_01"              , name: "Plage Femme 1"             , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_beach_02"              , name: "Plage Femme 2"             , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_bevhills_01"           , name: "Beverly Hills F1"          , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_bevhills_02"           , name: "Beverly Hills F2"          , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_bevhills_03"           , name: "Beverly Hills F3"          , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_bevhills_04"           , name: "Beverly Hills F4"          , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_business_01"           , name: "Business Femme 1"          , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_business_02"           , name: "Business Femme 2"          , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_business_03"           , name: "Business Femme 3"          , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_business_04"           , name: "Business Femme 4"          , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_eastsa_01"             , name: "East SA Femme 1"           , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_eastsa_02"             , name: "East SA Femme 2"           , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_eastsa_03"             , name: "East SA Femme 3"           , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_epsilon_01"            , name: "Epsilon Femme"             , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_fitness_01"            , name: "Fitness Femme 1"           , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_fitness_02"            , name: "Fitness Femme 2"           , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_genhot_01"             , name: "Femme Sexy"                , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_golfer_01"             , name: "Golfeuse"                  , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_hiker_01"              , name: "Randonneuse"               , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_indian_01"             , name: "Indienne"                  , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_juggalo_01"            , name: "Juggalo Femme"             , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_runner_01"             , name: "Joggeuse"                  , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_rurmeth_01"            , name: "Cambrousse Meth"           , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_scdressy_01"           , name: "South Central Chic"        , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_skater_01"             , name: "Skateuse"                  , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_soucent_01"            , name: "South Central F1"          , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_soucent_02"            , name: "South Central F2"          , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_soucent_03"            , name: "South Central F3"          , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_tennis_01"             , name: "Joueuse Tennis"            , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_topless_01"            , name: "Topless"                   , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_tourist_01"            , name: "Touriste Femme 1"          , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_tourist_02"            , name: "Touriste Femme 2"          , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_vinewood_01"           , name: "Vinewood Femme 1"          , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_vinewood_02"           , name: "Vinewood Femme 2"          , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_vinewood_03"           , name: "Vinewood Femme 3"          , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_vinewood_04"           , name: "Vinewood Femme 4"          , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_yoga_01"               , name: "Yoga Femme"                , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_clubcust_01"           , name: "Cliente Club 1"            , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_clubcust_02"           , name: "Cliente Club 2"            , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_clubcust_03"           , name: "Cliente Club 3"            , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_smartcaspat_01"        , name: "Smart Casual Femme"        , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_beach_01"              , name: "Plage Adulte 1"            , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_beach_02"              , name: "Plage Adulte 2"            , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_bevhills_01"           , name: "Beverly Hills M1"          , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_bevhills_02"           , name: "Beverly Hills M2"          , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_business_01"           , name: "Business Homme 1"          , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_eastsa_01"             , name: "East SA Adulte 1"          , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_eastsa_02"             , name: "East SA Adulte 2"          , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_farmer_01"             , name: "Fermier"                   , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_fatlatin_01"           , name: "Latin Gros"                , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_genfat_01"             , name: "Gros Generique 1"          , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_genfat_02"             , name: "Gros Generique 2"          , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_golfer_01"             , name: "Golfeur Adulte"            , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_hasjew_01"             , name: "Juif Hassidique M"         , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_hillbilly_01"          , name: "Campagnard 1"              , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_hillbilly_02"          , name: "Campagnard 2"              , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_indian_01"             , name: "Indien Adulte"             , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_ktown_01"              , name: "Koreatown Adulte"          , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_malibu_01"             , name: "Malibu"                    , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_mexcntry_01"           , name: "Campagnard Mex"            , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_mexlabor_01"           , name: "Ouvrier Mexicain"          , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_og_boss_01"            , name: "OG Boss"                   , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_paparazzi_01"          , name: "Paparazzi"                 , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_polynesian_01"         , name: "Polynesien Adulte"         , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_prolhost_01"           , name: "Prologue Host"             , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_rurmeth_01"            , name: "Campagne Meth"             , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_salton_01"             , name: "Salton Sea M1"             , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_salton_02"             , name: "Salton Sea M2"             , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_salton_03"             , name: "Salton Sea M3"             , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_salton_04"             , name: "Salton Sea M4"             , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_skater_01"             , name: "Skater Adulte"             , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_skidrow_01"            , name: "Skid Row Adulte"           , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_socenlat_01"           , name: "South Central Lat."        , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_soucent_01"            , name: "South Central M1"          , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_soucent_02"            , name: "South Central M2"          , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_soucent_03"            , name: "South Central M3"          , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_soucent_04"            , name: "South Central M4"          , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_stlat_02"              , name: "Latino Rue Adulte"         , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_tennis_01"             , name: "Tennis Adulte"             , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_tourist_01"            , name: "Touriste Homme"            , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_tramp_01"              , name: "Clochard 1"                , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_trampbeac_01"          , name: "Clochard Plage"            , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_tranvest_01"           , name: "Travesti 1"                , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_tranvest_02"           , name: "Travesti 2"                , cat: "street"    , tier: "gold"     },
  { model: "a_f_m_beach_01"              , name: "Plage Adulte F1"           , cat: "street"    , tier: "gold"     },
  { model: "a_f_m_bevhills_01"           , name: "Beverly Hills FM1"         , cat: "street"    , tier: "gold"     },
  { model: "a_f_m_bevhills_02"           , name: "Beverly Hills FM2"         , cat: "street"    , tier: "gold"     },
  { model: "a_f_m_bodybuild_01"          , name: "Bodybuildeuse"             , cat: "street"    , tier: "gold"     },
  { model: "a_f_m_business_02"           , name: "Business FM2"              , cat: "street"    , tier: "gold"     },
  { model: "a_f_m_downtown_01"           , name: "Downtown Femme"            , cat: "street"    , tier: "gold"     },
  { model: "a_f_m_eastsa_01"             , name: "East SA FM1"               , cat: "street"    , tier: "gold"     },
  { model: "a_f_m_eastsa_02"             , name: "East SA FM2"               , cat: "street"    , tier: "gold"     },
  { model: "a_f_m_fatbla_01"             , name: "Grosse Noire"              , cat: "street"    , tier: "gold"     },
  { model: "a_f_m_fatcult_01"            , name: "Grosse Secte"              , cat: "street"    , tier: "gold"     },
  { model: "a_f_m_fatwhite_01"           , name: "Grosse Blanche"            , cat: "street"    , tier: "gold"     },
  { model: "a_f_m_ktown_01"              , name: "Koreatown FM"              , cat: "street"    , tier: "gold"     },
  { model: "a_f_m_ktown_02"              , name: "Koreatown FM2"             , cat: "street"    , tier: "gold"     },
  { model: "a_f_m_prolhost_01"           , name: "Prologue Host F"           , cat: "street"    , tier: "gold"     },
  { model: "a_f_m_salton_01"             , name: "Salton Sea FM"             , cat: "street"    , tier: "gold"     },
  { model: "a_f_m_skidrow_01"            , name: "Skid Row Femme"            , cat: "street"    , tier: "gold"     },
  { model: "a_f_m_soucent_01"            , name: "South Central FM1"         , cat: "street"    , tier: "gold"     },
  { model: "a_f_m_soucent_02"            , name: "South Central FM2"         , cat: "street"    , tier: "gold"     },
  { model: "a_f_m_soucentmc_01"          , name: "South Central MC F"        , cat: "street"    , tier: "gold"     },
  { model: "a_f_m_tourist_01"            , name: "Touriste FM"               , cat: "street"    , tier: "gold"     },
  { model: "a_f_m_tramp_01"              , name: "Clocharde"                 , cat: "street"    , tier: "gold"     },
  { model: "a_f_m_trampbeac_01"          , name: "Clocharde Plage"           , cat: "street"    , tier: "gold"     },
  { model: "a_m_o_acult_01"              , name: "Secte Vieux 1"             , cat: "street"    , tier: "gold"     },
  { model: "a_m_o_acult_02"              , name: "Secte Vieux 2"             , cat: "street"    , tier: "gold"     },
  { model: "a_m_o_beach_01"              , name: "Vieux Plage"               , cat: "street"    , tier: "gold"     },
  { model: "a_m_o_genstreet_01"          , name: "Vieux Rue"                 , cat: "street"    , tier: "gold"     },
  { model: "a_m_o_ktown_01"              , name: "Vieux Koreatown"           , cat: "street"    , tier: "gold"     },
  { model: "a_m_o_salton_01"             , name: "Vieux Salton"              , cat: "street"    , tier: "gold"     },
  { model: "a_m_o_soucent_01"            , name: "Vieux South Central 1"     , cat: "street"    , tier: "gold"     },
  { model: "a_m_o_soucent_02"            , name: "Vieux South Central 2"     , cat: "street"    , tier: "gold"     },
  { model: "a_m_o_soucent_03"            , name: "Vieux South Central 3"     , cat: "street"    , tier: "gold"     },
  { model: "a_m_o_tramp_01"              , name: "Vieux Clochard"            , cat: "street"    , tier: "gold"     },
  { model: "a_f_o_genstreet_01"          , name: "Vieille Rue"               , cat: "street"    , tier: "gold"     },
  { model: "a_f_o_indian_01"             , name: "Vieille Indienne"          , cat: "street"    , tier: "gold"     },
  { model: "a_f_o_ktown_01"              , name: "Vieille Koreatown"         , cat: "street"    , tier: "gold"     },
  { model: "a_f_o_salton_01"             , name: "Vieille Salton"            , cat: "street"    , tier: "gold"     },
  { model: "a_f_o_soucent_01"            , name: "Vieille South Cent. 1"     , cat: "street"    , tier: "gold"     },
  { model: "a_f_o_soucent_02"            , name: "Vieille South Cent. 2"     , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_fatbla_01"             , name: "Gros Noir"                 , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_acult_01"              , name: "Secte Homme 1"             , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_acult_01"              , name: "Secte Jeune 1"             , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_acult_02"              , name: "Secte Jeune 2"             , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_acult_02"              , name: "Secte Homme 2"             , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_obese_01"              , name: "Obese"                     , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_mlcrisis_01"           , name: "Crise Midlife"             , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_smartcaspat_01"        , name: "Smart Casual"              , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_stlat_01"              , name: "Latino Rue M1"             , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_vindouche_01"          , name: "Vinewood Douche"           , cat: "street"    , tier: "gold"     },
  { model: "a_m_m_prolsec_01"            , name: "Securite Prologue M"       , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_prolsec_01"            , name: "Securite Prologue Y"       , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_nbhdsouth_01"          , name: "Quartier Sud"              , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_femaleagent"           , name: "Agent Femme"               , cat: "street"    , tier: "gold"     },
  { model: "a_f_y_gencaspat_01"          , name: "Casual Femme"              , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_gendrugwrk_01"         , name: "Ouvrier Drogue"            , cat: "street"    , tier: "gold"     },
  { model: "a_m_y_gendrugwrk_02"         , name: "Ouvrier Drogue 2"          , cat: "street"    , tier: "gold"     },

  // ── BUSINESS ────────────────────────────────────────────────────────
  { model: "a_m_y_business_01"           , name: "Business Jeune 1"          , cat: "business"  , tier: "gold"     },
  { model: "a_m_y_business_02"           , name: "Business Jeune 2"          , cat: "business"  , tier: "gold"     },
  { model: "a_m_y_business_03"           , name: "Business Jeune 3"          , cat: "business"  , tier: "gold"     },
  { model: "a_m_m_afriamer_01"           , name: "Afro-Americain"            , cat: "business"  , tier: "gold"     },
  { model: "a_m_m_bankrobber_01"         , name: "Braqueur"                  , cat: "business"  , tier: "gold"     },
  { model: "a_m_m_suits_01"              , name: "Homme Costume 1"           , cat: "business"  , tier: "gold"     },
  { model: "a_m_m_suits_02"              , name: "Homme Costume 2"           , cat: "business"  , tier: "gold"     },
  { model: "a_f_m_business_01"           , name: "Business FM1"              , cat: "business"  , tier: "gold"     },

  // ── WORKER / SERVICE ────────────────────────────────────────────────
  { model: "s_m_y_construct_01"          , name: "Ouvrier BTP 1"             , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_construct_02"          , name: "Ouvrier BTP 2"             , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_autoshop_01"           , name: "Mecanicien Auto 1"         , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_autoshop_02"           , name: "Mecanicien Auto 2"         , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_doctor_01"             , name: "Docteur"                   , cat: "worker"    , tier: "gold"     },
  { model: "s_f_y_scrubs_01"             , name: "Infirmiere"                , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_ammucity_01"           , name: "Vendeur Ammunation"        , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_ammucountry"           , name: "Vendeur Ammu Rural"        , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_airworker"             , name: "Agent Aeroport"            , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_barman_01"             , name: "Barman"                    , cat: "worker"    , tier: "gold"     },
  { model: "s_f_y_bartender_01"          , name: "Barmaid"                   , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_baywatch_01"           , name: "Sauveteur Plage"           , cat: "worker"    , tier: "gold"     },
  { model: "s_f_y_baywatch_01"           , name: "Sauveteuse Plage"          , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_busboy_01"             , name: "Garcon Cafe"               , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_chef_01"               , name: "Cuisinier"                 , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_clown_01"              , name: "Clown Travail"             , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_dealer_01"             , name: "Dealer"                    , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_devinsec_01"           , name: "Securite Devin"            , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_dockwork_01"           , name: "Docker"                    , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_doorman_01"            , name: "Portier"                   , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_dwservice_01"          , name: "Service Eau 1"             , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_dwservice_02"          , name: "Service Eau 2"             , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_fieldworker_01"        , name: "Ouvrier Champ"             , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_fireman_01"            , name: "Pompier"                   , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_gaffer_01"             , name: "Technicien Plateau"        , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_garbage"               , name: "Eboueur"                   , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_gardener_01"           , name: "Jardinier"                 , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_gentransport"          , name: "Transporteur"              , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_hairdress_01"          , name: "Coiffeur"                  , cat: "worker"    , tier: "gold"     },
  { model: "s_f_y_hooker_01"             , name: "Prostituee 1"              , cat: "worker"    , tier: "gold"     },
  { model: "s_f_y_hooker_02"             , name: "Prostituee 2"              , cat: "worker"    , tier: "gold"     },
  { model: "s_f_y_hooker_03"             , name: "Prostituee 3"              , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_janitor"               , name: "Concierge"                 , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_lathandy_01"           , name: "Latino Bricoleur"          , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_lifeinvad_01"          , name: "LifeInvader"               , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_linecook"              , name: "Cuistot Ligne"             , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_lsmetro_01"            , name: "Metro LS"                  , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_mariachi_01"           , name: "Mariachi"                  , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_migrant_01"            , name: "Migrant"                   , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_movalien_01"           , name: "Alien Film"                , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_movprem_01"            , name: "Acteur Premier"            , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_movspace_01"           , name: "Astronaute Film"           , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_mime"                  , name: "Mime"                      , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_pestcont_01"           , name: "Anti-Nuisibles"            , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_paramedic_01"          , name: "Ambulancier"               , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_postal_01"             , name: "Facteur 1"                 , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_postal_02"             , name: "Facteur 2"                 , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_robber_01"             , name: "Voleur"                    , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_scientist_01"          , name: "Scientifique"              , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_shop_mask"             , name: "Vendeur Masques"           , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_strvend_01"            , name: "Vendeur Rue"               , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_strperf_01"            , name: "Artiste Rue 1"             , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_strpreach_01"          , name: "Precheur Rue"              , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_stripper_01"           , name: "Stripteaseur"              , cat: "worker"    , tier: "gold"     },
  { model: "s_f_y_stripper_01"           , name: "Stripteaseuse W1"          , cat: "worker"    , tier: "gold"     },
  { model: "s_f_y_stripper_02"           , name: "Stripteaseuse W2"          , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_strvend_01"            , name: "Vendeur Ambulant"          , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_trucker_01"            , name: "Routier"                   , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_valet_01"              , name: "Voiturier"                 , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_waiter_01"             , name: "Serveur"                   , cat: "worker"    , tier: "gold"     },
  { model: "s_f_y_sweatshop_01"          , name: "Ouvriere Atelier"          , cat: "worker"    , tier: "gold"     },
  { model: "s_f_y_shop_low"              , name: "Vendeuse Discount"         , cat: "worker"    , tier: "gold"     },
  { model: "s_f_y_shop_mid"              , name: "Vendeuse Boutique"         , cat: "worker"    , tier: "gold"     },
  { model: "s_f_y_shop_high"             , name: "Vendeuse Luxe"             , cat: "worker"    , tier: "gold"     },
  { model: "s_f_m_fembarber"             , name: "Barbiere"                  , cat: "worker"    , tier: "gold"     },
  { model: "s_f_m_maid_01"               , name: "Femme Menage"              , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_ccrew_01"              , name: "Equipe Chantier"           , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_cntrybar_01"           , name: "Barman Campagne"           , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_dockwork_01"           , name: "Docker Adulte"             , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_factory_01"            , name: "Ouvrier Usine"             , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_grip_01"               , name: "Machiniste Film"           , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_drug_01"               , name: "Drogue"                    , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_westsec_01"            , name: "Securite Ouest"            , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_westsec_02"            , name: "Securite Ouest 2"          , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_winclean_01"           , name: "Laveur Vitres"             , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_xmech_01"              , name: "Mecanicien X 1"            , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_xmech_02"              , name: "Mecanicien X 2"            , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_movAlien_01"           , name: "Alien Film 2"              , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_autopsy_01"            , name: "Legiste"                   , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_highsec_01"            , name: "Securite VIP 1"            , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_highsec_02"            , name: "Securite VIP 2"            , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_clubbar_01"            , name: "Barman Club"               , cat: "worker"    , tier: "gold"     },
  { model: "s_f_y_clubbar_01"            , name: "Barmaid Club"              , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_casino_01"             , name: "Employe Casino"            , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_corpse_01"             , name: "Corps Homme"               , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_movstar_01"            , name: "Star Cinema Homme"         , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_rapper_01"             , name: "Rappeur"                   , cat: "worker"    , tier: "gold"     },
  { model: "s_m_y_mushmush_01"           , name: "Champignon"                , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_ups_01"                , name: "Livreur UPS"               , cat: "worker"    , tier: "gold"     },
  { model: "s_m_m_ups_02"                , name: "Livreur UPS 2"             , cat: "worker"    , tier: "gold"     },

  // ── STORY CHARACTERS ────────────────────────────────────────────────
  // Michael/Franklin/Trevor (player_zero/one/two) volontairement absents :
  // ce sont les hash des protagonistes solo, blacklistés côté serveur
  // (isValidPedModel) — les lister ici ne faisait que produire une carte
  // sélectionnable qui se faisait rejeter silencieusement à la confirmation.
  { model: "ig_amanda"                   , name: "Amanda"                    , cat: "story"     , tier: "diamond"  },
  { model: "ig_tracydisanto"             , name: "Tracy"                     , cat: "story"     , tier: "diamond"  },
  { model: "ig_jimmydisanto"             , name: "Jimmy"                     , cat: "story"     , tier: "diamond"  },
  { model: "ig_lamar"                    , name: "Lamar"                     , cat: "story"     , tier: "diamond"  },
  { model: "ig_stretch"                  , name: "Stretch"                   , cat: "story"     , tier: "diamond"  },
  { model: "ig_tanisha"                  , name: "Tanisha"                   , cat: "story"     , tier: "diamond"  },
  { model: "ig_denise"                   , name: "Denise"                    , cat: "story"     , tier: "diamond"  },
  { model: "ig_floyd"                    , name: "Floyd"                     , cat: "story"     , tier: "diamond"  },
  { model: "ig_wade"                     , name: "Wade"                      , cat: "story"     , tier: "diamond"  },
  { model: "ig_ron"                      , name: "Ron"                       , cat: "story"     , tier: "diamond"  },
  { model: "ig_patricia"                 , name: "Patricia"                  , cat: "story"     , tier: "diamond"  },
  { model: "ig_nervousron"               , name: "Ron (Nerveux)"             , cat: "story"     , tier: "diamond"  },
  { model: "ig_mrk"                      , name: "Mr. K"                     , cat: "story"     , tier: "diamond"  },
  { model: "ig_devin"                    , name: "Devin Weston"              , cat: "story"     , tier: "diamond"  },
  { model: "ig_davids"                   , name: "Dave Norton"               , cat: "story"     , tier: "diamond"  },
  { model: "ig_stevehains"               , name: "Steve Haines"              , cat: "story"     , tier: "diamond"  },
  { model: "ig_andreas"                  , name: "Andreas"                   , cat: "story"     , tier: "diamond"  },
  { model: "ig_solomon"                  , name: "Solomon Richards"          , cat: "story"     , tier: "diamond"  },
  { model: "ig_martin"                   , name: "Martin Madrazo"            , cat: "story"     , tier: "diamond"  },
  { model: "ig_lazlow"                   , name: "Lazlow"                    , cat: "story"     , tier: "diamond"  },
  { model: "ig_lifeinvad_01"             , name: "Jay Norris"                , cat: "story"     , tier: "diamond"  },
  { model: "ig_lifeinvad_02"             , name: "LifeInvader Gars"          , cat: "story"     , tier: "diamond"  },
  { model: "ig_chef"                     , name: "Chef"                      , cat: "story"     , tier: "diamond"  },
  { model: "ig_chef2"                    , name: "Chef 2"                    , cat: "story"     , tier: "diamond"  },
  { model: "ig_chengsr"                  , name: "Wei Cheng"                 , cat: "story"     , tier: "diamond"  },
  { model: "ig_chrisformage"             , name: "Chris Formage"             , cat: "story"     , tier: "diamond"  },
  { model: "ig_brad"                     , name: "Brad"                      , cat: "story"     , tier: "diamond"  },
  { model: "ig_ballasog"                 , name: "Ballas OG"                 , cat: "story"     , tier: "diamond"  },
  { model: "ig_bankman"                  , name: "Banquier"                  , cat: "story"     , tier: "diamond"  },
  { model: "ig_barry"                    , name: "Barry"                     , cat: "story"     , tier: "diamond"  },
  { model: "ig_bestmen"                  , name: "Temoin Mariage"            , cat: "story"     , tier: "diamond"  },
  { model: "ig_beverly"                  , name: "Beverly"                   , cat: "story"     , tier: "diamond"  },
  { model: "ig_car3guy1"                 , name: "Gars Voiture 1"            , cat: "story"     , tier: "diamond"  },
  { model: "ig_car3guy2"                 , name: "Gars Voiture 2"            , cat: "story"     , tier: "diamond"  },
  { model: "ig_casey"                    , name: "Casey"                     , cat: "story"     , tier: "diamond"  },
  { model: "ig_clay"                     , name: "Clay"                      , cat: "story"     , tier: "diamond"  },
  { model: "ig_claypain"                 , name: "Clay (Biker)"              , cat: "story"     , tier: "diamond"  },
  { model: "ig_cletus"                   , name: "Cletus"                    , cat: "story"     , tier: "diamond"  },
  { model: "ig_dale"                     , name: "Dale"                      , cat: "story"     , tier: "diamond"  },
  { model: "ig_davenorton"               , name: "Dave Norton 2"             , cat: "story"     , tier: "diamond"  },
  { model: "ig_dom"                      , name: "Dom"                       , cat: "story"     , tier: "diamond"  },
  { model: "ig_dreyfuss"                 , name: "Peter Dreyfuss"            , cat: "story"     , tier: "diamond"  },
  { model: "ig_drfriedlander"            , name: "Dr. Friedlander"           , cat: "story"     , tier: "diamond"  },
  { model: "ig_fabien"                   , name: "Fabien"                    , cat: "story"     , tier: "diamond"  },
  { model: "ig_fbisuit_01"               , name: "FBI Costume"               , cat: "story"     , tier: "diamond"  },
  { model: "ig_groom"                    , name: "Marie"                     , cat: "story"     , tier: "diamond"  },
  { model: "ig_hao"                      , name: "Hao"                       , cat: "story"     , tier: "diamond"  },
  { model: "ig_hunter"                   , name: "Chasseur"                  , cat: "story"     , tier: "diamond"  },
  { model: "ig_janet"                    , name: "Janet"                     , cat: "story"     , tier: "diamond"  },
  { model: "ig_jay_norris"               , name: "Jay Norris 2"              , cat: "story"     , tier: "diamond"  },
  { model: "ig_jewelass"                 , name: "Bijoutier"                 , cat: "story"     , tier: "diamond"  },
  { model: "ig_jimmyboston"              , name: "Jimmy Boston"              , cat: "story"     , tier: "diamond"  },
  { model: "ig_johnnyklebitz"            , name: "Johnny Klebitz"            , cat: "story"     , tier: "diamond"  },
  { model: "ig_josef"                    , name: "Josef"                     , cat: "story"     , tier: "diamond"  },
  { model: "ig_josh"                     , name: "Josh"                      , cat: "story"     , tier: "diamond"  },
  { model: "ig_karen_daniels"            , name: "Karen Daniels"             , cat: "story"     , tier: "diamond"  },
  { model: "ig_kerrymcintosh"            , name: "Kerry McIntosh"            , cat: "story"     , tier: "diamond"  },
  { model: "ig_lamardavis"               , name: "Lamar Davis"               , cat: "story"     , tier: "diamond"  },
  { model: "ig_lestercrest"              , name: "Lester"                    , cat: "story"     , tier: "diamond"  },
  { model: "ig_lestercrest_2"            , name: "Lester 2"                  , cat: "story"     , tier: "diamond"  },
  { model: "ig_magenta"                  , name: "Magenta"                   , cat: "story"     , tier: "diamond"  },
  { model: "ig_malc"                     , name: "Malc"                      , cat: "story"     , tier: "diamond"  },
  { model: "ig_manuel"                   , name: "Manuel"                    , cat: "story"     , tier: "diamond"  },
  { model: "ig_marnie"                   , name: "Marnie"                    , cat: "story"     , tier: "diamond"  },
  { model: "ig_maryann"                  , name: "Mary Ann"                  , cat: "story"     , tier: "diamond"  },
  { model: "ig_maude"                    , name: "Maude"                     , cat: "story"     , tier: "diamond"  },
  { model: "ig_michelle"                 , name: "Michelle"                  , cat: "story"     , tier: "diamond"  },
  { model: "ig_milton"                   , name: "Milton"                    , cat: "story"     , tier: "diamond"  },
  { model: "ig_molly"                    , name: "Molly"                     , cat: "story"     , tier: "diamond"  },
  { model: "ig_money"                    , name: "Argent"                    , cat: "story"     , tier: "diamond"  },
  { model: "ig_mp_agent14"               , name: "Agent 14"                  , cat: "story"     , tier: "diamond"  },
  { model: "ig_mrs_thornhill"            , name: "Mme Thornhill"             , cat: "story"     , tier: "diamond"  },
  { model: "ig_mrsphillips"              , name: "Mme Phillips"              , cat: "story"     , tier: "diamond"  },
  { model: "ig_natalia"                  , name: "Natalia"                   , cat: "story"     , tier: "diamond"  },
  { model: "ig_nigel"                    , name: "Nigel"                     , cat: "story"     , tier: "diamond"  },
  { model: "ig_old_man1a"                , name: "Vieil Homme 1"             , cat: "story"     , tier: "diamond"  },
  { model: "ig_old_man2"                 , name: "Vieil Homme 2"             , cat: "story"     , tier: "diamond"  },
  { model: "ig_omega"                    , name: "Omega"                     , cat: "story"     , tier: "diamond"  },
  { model: "ig_oneil"                    , name: "O'Neil"                    , cat: "story"     , tier: "diamond"  },
  { model: "ig_orleans"                  , name: "Orleans"                   , cat: "story"     , tier: "diamond"  },
  { model: "ig_ortega"                   , name: "Ortega"                    , cat: "story"     , tier: "diamond"  },
  { model: "ig_paige"                    , name: "Paige"                     , cat: "story"     , tier: "diamond"  },
  { model: "ig_paper"                    , name: "Paper"                     , cat: "story"     , tier: "diamond"  },
  { model: "ig_popov"                    , name: "Popov"                     , cat: "story"     , tier: "diamond"  },
  { model: "ig_priest"                   , name: "Pretre"                    , cat: "story"     , tier: "diamond"  },
  { model: "ig_prolsec_02"               , name: "Securite Prologue"         , cat: "story"     , tier: "diamond"  },
  { model: "ig_ramp_gang"                , name: "Gang Rampe"                , cat: "story"     , tier: "diamond"  },
  { model: "ig_ramp_hic"                 , name: "Campagnard Rampe"          , cat: "story"     , tier: "diamond"  },
  { model: "ig_ramp_hipster"             , name: "Hipster Rampe"             , cat: "story"     , tier: "diamond"  },
  { model: "ig_ramp_mex"                 , name: "Mexicain Rampe"            , cat: "story"     , tier: "diamond"  },
  { model: "ig_rashcosvki"               , name: "Rashkovsky"                , cat: "story"     , tier: "diamond"  },
  { model: "ig_roccopelosi"              , name: "Rocco Pelosi"              , cat: "story"     , tier: "diamond"  },
  { model: "ig_russiandrunk"             , name: "Russe Bourre"              , cat: "story"     , tier: "diamond"  },
  { model: "ig_screen_writer"            , name: "Scenariste"                , cat: "story"     , tier: "diamond"  },
  { model: "ig_siemonyetarian"           , name: "Simeon"                    , cat: "story"     , tier: "diamond"  },
  { model: "ig_skinny"                   , name: "Skinny"                    , cat: "story"     , tier: "diamond"  },
  { model: "ig_talina"                   , name: "Talina"                    , cat: "story"     , tier: "diamond"  },
  { model: "ig_taocheng"                 , name: "Tao Cheng"                 , cat: "story"     , tier: "diamond"  },
  { model: "ig_taostranslator"           , name: "Traducteur Tao"            , cat: "story"     , tier: "diamond"  },
  { model: "ig_tenniscoach"              , name: "Coach Tennis"              , cat: "story"     , tier: "diamond"  },
  { model: "ig_terry"                    , name: "Terry"                     , cat: "story"     , tier: "diamond"  },
  { model: "ig_tomepsilon"               , name: "Tom Epsilon"               , cat: "story"     , tier: "diamond"  },
  { model: "ig_tonya"                    , name: "Tonya"                     , cat: "story"     , tier: "diamond"  },
  { model: "ig_tylerdix"                 , name: "Tyler"                     , cat: "story"     , tier: "diamond"  },
  { model: "ig_zimbor"                   , name: "Zimbor"                    , cat: "story"     , tier: "diamond"  },
  { model: "ig_benny"                    , name: "Benny"                     , cat: "story"     , tier: "diamond"  },
  { model: "ig_djblamadon"               , name: "Black Madonna"             , cat: "story"     , tier: "diamond"  },
  { model: "ig_djblamrupert"             , name: "DJ Rupert"                 , cat: "story"     , tier: "diamond"  },
  { model: "ig_djdixmanager"             , name: "Manager Dixon"             , cat: "story"     , tier: "diamond"  },
  { model: "ig_djgeneric_01"             , name: "DJ Generique"              , cat: "story"     , tier: "diamond"  },
  { model: "ig_djsolfotios"              , name: "Solomun"                   , cat: "story"     , tier: "diamond"  },
  { model: "ig_djtalaurelia"             , name: "Tale Of Us"                , cat: "story"     , tier: "diamond"  },
  { model: "ig_djtalignDLC"              , name: "Dixon"                     , cat: "story"     , tier: "diamond"  },
  { model: "ig_isldj_00"                 , name: "DJ Iles 1"                 , cat: "story"     , tier: "diamond"  },
  { model: "ig_isldj_01"                 , name: "DJ Iles 2"                 , cat: "story"     , tier: "diamond"  },
  { model: "ig_isldj_02"                 , name: "DJ Iles 3"                 , cat: "story"     , tier: "diamond"  },
  { model: "ig_isldj_03"                 , name: "DJ Iles 4"                 , cat: "story"     , tier: "diamond"  },
  { model: "ig_isldj_04"                 , name: "DJ Iles 5"                 , cat: "story"     , tier: "diamond"  },
  { model: "ig_kaylee"                   , name: "Kaylee"                    , cat: "story"     , tier: "diamond"  },
  { model: "ig_jackie"                   , name: "Jackie"                    , cat: "story"     , tier: "diamond"  },
  { model: "ig_wendy"                    , name: "Wendy"                     , cat: "story"     , tier: "diamond"  },
  { model: "ig_agatha"                   , name: "Agatha Baker"              , cat: "story"     , tier: "diamond"  },
  { model: "ig_brucie"                   , name: "Brucie Kibbutz"            , cat: "story"     , tier: "diamond"  },
  { model: "ig_ashley"                   , name: "Ashley"                    , cat: "story"     , tier: "diamond"  },
  { model: "ig_bankman_02"               , name: "Banquier 2"                , cat: "story"     , tier: "diamond"  },
  { model: "ig_daveNorton"               , name: "Dave Norton Full"          , cat: "story"     , tier: "diamond"  },

  // ── HEIST / CUTSCENE ────────────────────────────────────────────────
  { model: "ig_abigail"                  , name: "Abigail"                   , cat: "heist"     , tier: "diamond"  },
  { model: "ig_agent"                    , name: "Agent"                     , cat: "heist"     , tier: "diamond"  },
  { model: "ig_englishdave"              , name: "English Dave"              , cat: "heist"     , tier: "diamond"  },
  { model: "ig_g"                        , name: "Gerald"                    , cat: "heist"     , tier: "diamond"  },
  { model: "ig_gustavo"                  , name: "Gustavo"                   , cat: "heist"     , tier: "diamond"  },
  { model: "ig_tomcasino"                , name: "Tom (Casino)"              , cat: "heist"     , tier: "diamond"  },
  { model: "ig_thornton"                 , name: "Thornton"                  , cat: "heist"     , tier: "diamond"  },
  { model: "ig_vincent"                  , name: "Vincent"                   , cat: "heist"     , tier: "diamond"  },
  { model: "ig_avon"                     , name: "Avon Hertz"                , cat: "heist"     , tier: "diamond"  },
  { model: "ig_brucie2"                  , name: "Brucie"                    , cat: "heist"     , tier: "diamond"  },
  { model: "ig_celeb_01"                 , name: "Celebrite 1"               , cat: "heist"     , tier: "diamond"  },
  { model: "ig_georgina"                 , name: "Georgina Cheng"            , cat: "heist"     , tier: "diamond"  },
  { model: "csb_agent"                   , name: "Agent (CSB)"               , cat: "heist"     , tier: "diamond"  },
  { model: "csb_avon"                    , name: "Avon (CSB)"                , cat: "heist"     , tier: "diamond"  },
  { model: "csb_bogdan"                  , name: "Bogdan"                    , cat: "heist"     , tier: "diamond"  },
  { model: "csb_chef"                    , name: "Chef (CSB)"                , cat: "heist"     , tier: "diamond"  },
  { model: "csb_chef2"                   , name: "Chef 2 (CSB)"              , cat: "heist"     , tier: "diamond"  },
  { model: "csb_chin_goon"               , name: "Goon Chinois"              , cat: "heist"     , tier: "diamond"  },
  { model: "csb_cletus"                  , name: "Cletus (CSB)"              , cat: "heist"     , tier: "diamond"  },
  { model: "csb_cop"                     , name: "Flic (CSB)"                , cat: "heist"     , tier: "diamond"  },
  { model: "csb_customer"                , name: "Client (CSB)"              , cat: "heist"     , tier: "diamond"  },
  { model: "csb_denise_friend"           , name: "Amie Denise"               , cat: "heist"     , tier: "diamond"  },
  { model: "csb_englishdave"             , name: "English Dave (CSB)"        , cat: "heist"     , tier: "diamond"  },
  { model: "csb_fos_rep"                 , name: "Rep FOS"                   , cat: "heist"     , tier: "diamond"  },
  { model: "csb_g"                       , name: "Gerald (CSB)"              , cat: "heist"     , tier: "diamond"  },
  { model: "csb_georgina"                , name: "Georgina (CSB)"            , cat: "heist"     , tier: "diamond"  },
  { model: "csb_groove_str"              , name: "Grove Street"              , cat: "heist"     , tier: "diamond"  },
  { model: "csb_gustavo"                 , name: "Gustavo (CSB)"             , cat: "heist"     , tier: "diamond"  },
  { model: "csb_hao"                     , name: "Hao (CSB)"                 , cat: "heist"     , tier: "diamond"  },
  { model: "csb_hugh"                    , name: "Hugh"                      , cat: "heist"     , tier: "diamond"  },
  { model: "csb_imran"                   , name: "Imran"                     , cat: "heist"     , tier: "diamond"  },
  { model: "csb_janitor"                 , name: "Concierge"                 , cat: "heist"     , tier: "diamond"  },
  { model: "csb_jio"                     , name: "Jio"                       , cat: "heist"     , tier: "diamond"  },
  { model: "csb_karen_daniels"           , name: "Karen (CSB)"               , cat: "heist"     , tier: "diamond"  },
  { model: "csb_mp_agent14"              , name: "Agent 14 (CSB)"            , cat: "heist"     , tier: "diamond"  },
  { model: "csb_mrs_r"                   , name: "Mme R"                     , cat: "heist"     , tier: "diamond"  },
  { model: "csb_mweather"                , name: "Merryweather"              , cat: "heist"     , tier: "diamond"  },
  { model: "csb_oscar"                   , name: "Oscar"                     , cat: "heist"     , tier: "diamond"  },
  { model: "csb_paige"                   , name: "Paige (CSB)"               , cat: "heist"     , tier: "diamond"  },
  { model: "csb_popov"                   , name: "Popov (CSB)"               , cat: "heist"     , tier: "diamond"  },
  { model: "csb_porndude"                , name: "Type Porno"                , cat: "heist"     , tier: "diamond"  },
  { model: "csb_rashcosvki"              , name: "Rashkovsky (CSB)"          , cat: "heist"     , tier: "diamond"  },
  { model: "csb_reporter"                , name: "Reporter"                  , cat: "heist"     , tier: "diamond"  },
  { model: "csb_roccopelosi"             , name: "Rocco (CSB)"               , cat: "heist"     , tier: "diamond"  },
  { model: "csb_screen_writer"           , name: "Scenariste (CSB)"          , cat: "heist"     , tier: "diamond"  },
  { model: "csb_sol"                     , name: "Sol"                       , cat: "heist"     , tier: "diamond"  },
  { model: "csb_stripper_01"             , name: "Stripteaseuse 1"           , cat: "heist"     , tier: "diamond"  },
  { model: "csb_stripper_02"             , name: "Stripteaseuse 2"           , cat: "heist"     , tier: "diamond"  },
  { model: "csb_tonya"                   , name: "Tonya (CSB)"               , cat: "heist"     , tier: "diamond"  },
  { model: "csb_tomcasino"               , name: "Tom Casino (CSB)"          , cat: "heist"     , tier: "diamond"  },
  { model: "csb_thornton"                , name: "Thornton (CSB)"            , cat: "heist"     , tier: "diamond"  },
  { model: "csb_vincent"                 , name: "Vincent (CSB)"             , cat: "heist"     , tier: "diamond"  },
  { model: "csb_vagspeak"                , name: "Vagos Speaker"             , cat: "heist"     , tier: "diamond"  },
  { model: "csb_anita"                   , name: "Anita"                     , cat: "heist"     , tier: "diamond"  },
  { model: "csb_anton"                   , name: "Anton"                     , cat: "heist"     , tier: "diamond"  },
  { model: "csb_bride"                   , name: "Mariee"                    , cat: "heist"     , tier: "diamond"  },
  { model: "csb_burgerdrug"              , name: "Dealer Burger"             , cat: "heist"     , tier: "diamond"  },
  { model: "csb_car3guy1"                , name: "Gars Voiture (CSB)"        , cat: "heist"     , tier: "diamond"  },
  { model: "csb_car3guy2"                , name: "Gars Voiture 2 (CSB)"      , cat: "heist"     , tier: "diamond"  },
  { model: "csb_dix"                     , name: "Dix"                       , cat: "heist"     , tier: "diamond"  },
  { model: "csb_djblamadon"              , name: "DJ Black Madonna"          , cat: "heist"     , tier: "diamond"  },
  { model: "csb_djdixmanager"            , name: "Manager DJ Dix"            , cat: "heist"     , tier: "diamond"  },
  { model: "csb_djgeneric_01"            , name: "DJ Generique"              , cat: "heist"     , tier: "diamond"  },
  { model: "csb_djsolfotios"             , name: "Solomun"                   , cat: "heist"     , tier: "diamond"  },
  { model: "csb_djtalaurelia"            , name: "Tale Of Us"                , cat: "heist"     , tier: "diamond"  },
  { model: "csb_djtalignDLC"             , name: "Dixon"                     , cat: "heist"     , tier: "diamond"  },
  { model: "csb_drugdealer"              , name: "Dealer"                    , cat: "heist"     , tier: "diamond"  },
  { model: "csb_jackhowitzer"            , name: "Jack Howitzer"             , cat: "heist"     , tier: "diamond"  },
  { model: "csb_prolsec"                 , name: "Securite Prologue"         , cat: "heist"     , tier: "diamond"  },
  { model: "csb_trafficwarden"           , name: "Agent Circulation"         , cat: "heist"     , tier: "diamond"  },
  { model: "csb_undercover"              , name: "Agent Infiltre"            , cat: "heist"     , tier: "diamond"  },

  // ── HORROR ──────────────────────────────────────────────────────────
  // "Zombie 1" (u_m_y_zombie_01) et "Cadavre Homme 2" (u_m_y_corpse_02)
  // volontairement absents : ce sont des modèles réellement utilisés par les
  // zombies de pvp_zombies (voir CLAUDE.md) — un joueur à l'identique aurait
  // créé une confusion ami/ennemi en jeu.
  { model: "u_m_y_corpse_01"             , name: "Cadavre Homme"             , cat: "horror"    , tier: "diamond"  },
  { model: "u_f_y_corpse_02"             , name: "Cadavre Femme 2"           , cat: "horror"    , tier: "diamond"  },
  { model: "u_m_y_militarybum"           , name: "Militaire Clochard"        , cat: "horror"    , tier: "diamond"  },
  { model: "u_m_y_proldriver_01"         , name: "Conducteur Prologue"       , cat: "horror"    , tier: "diamond"  },

  // ── ANIMAL ──────────────────────────────────────────────────────────
  { model: "a_c_boar"                    , name: "Sanglier"                  , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_cat_01"                  , name: "Chat"                      , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_chickenhawk"             , name: "Faucon"                    , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_chimp"                   , name: "Chimpanze"                 , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_chop"                    , name: "Chop"                      , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_cormorant"               , name: "Cormoran"                  , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_cow"                     , name: "Vache"                     , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_coyote"                  , name: "Coyote"                    , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_crow"                    , name: "Corbeau"                   , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_deer"                    , name: "Cerf"                      , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_dolphin"                 , name: "Dauphin"                   , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_fish"                    , name: "Poisson"                   , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_hen"                     , name: "Poule"                     , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_humpback"                , name: "Baleine Bosse"             , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_husky"                   , name: "Husky"                     , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_killerwhale"             , name: "Orque"                     , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_mtlion"                  , name: "Puma"                      , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_pig"                     , name: "Cochon"                    , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_pigeon"                  , name: "Pigeon"                    , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_poodle"                  , name: "Caniche"                   , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_pug"                     , name: "Carlin"                    , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_rabbit_01"               , name: "Lapin"                     , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_rat"                     , name: "Rat"                       , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_retriever"               , name: "Golden Retriever"          , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_rhesus"                  , name: "Macaque"                   , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_rottweiler"              , name: "Rottweiler"                , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_seagull"                 , name: "Mouette"                   , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_sharkhammer"             , name: "Requin Marteau"            , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_sharktiger"              , name: "Requin Tigre"              , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_shepherd"                , name: "Berger Allemand"           , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_stingray"                , name: "Raie"                      , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_westy"                   , name: "Westie"                    , cat: "animal"    , tier: "diamond"  },
  { model: "a_c_panther"                 , name: "Panthere"                  , cat: "animal"    , tier: "diamond"  },

  // ── MISC / UNIQUE ───────────────────────────────────────────────────
  { model: "u_m_m_aldinapoli"            , name: "Al Di Napoli"              , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_m_bankman"               , name: "Banquier Unique"           , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_m_bikehire_01"           , name: "Loueur Velo"               , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_m_doa_01"                , name: "Mort 1"                    , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_m_edtoh"                 , name: "Ed Toh"                    , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_m_filmdirector"          , name: "Realisateur"               , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_m_glenstank_01"          , name: "Glen Stank"                , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_m_griff_01"              , name: "Griff"                     , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_m_jesus_01"              , name: "Jesus"                     , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_m_jewelthief"            , name: "Voleur Bijoux"             , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_m_markfost"              , name: "Mark Fost"                 , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_m_partytarget"           , name: "Cible Fete"                , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_m_promourn_01"           , name: "Endeuille"                 , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_m_rivalpap"              , name: "Paparazzi Rival"           , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_m_spyactor"              , name: "Acteur Espion"             , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_m_willyfist"             , name: "Willy Fist"                , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_o_finguru_01"            , name: "Guru Finance"              , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_o_taphillbilly"          , name: "Campagnard Tap"            , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_o_tramp_01"              , name: "Clochard Unique"           , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_y_abner"                 , name: "Abner"                     , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_y_antonb"                , name: "Anton B"                   , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_y_baygor"                , name: "Baygor"                    , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_y_burgerdrug_01"         , name: "Burger Drogue"             , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_y_chip"                  , name: "Chip"                      , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_y_cyclist_01"            , name: "Cycliste Unique"           , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_y_danceburl_01"          , name: "Danseur Burlesque"         , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_y_dancelthr_01"          , name: "Danseur Cuir"              , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_y_dancerave_01"          , name: "Danseur Rave"              , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_y_fibmugger_01"          , name: "Agresseur FIB"             , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_y_guido_01"              , name: "Guido"                     , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_y_gunvend_01"            , name: "Vendeur Armes"             , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_y_hippie_01"             , name: "Hippie"                    , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_y_imporage"              , name: "Import Rage"               , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_y_mani"                  , name: "Mani"                      , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_y_paparazzi"             , name: "Paparazzi Unique"          , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_y_party_01"              , name: "Fetard"                    , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_y_pogo_01"               , name: "Pogo"                      , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_y_sbike"                 , name: "Stunt Bike"                , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_y_smugmech_01"           , name: "Mecanicien Smug"           , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_y_staggrm_01"            , name: "Stag Party"                , cat: "misc"      , tier: "diamond"  },
  { model: "u_m_y_tattoo_01"             , name: "Tatoueur"                  , cat: "misc"      , tier: "diamond"  },
  { model: "u_f_m_corpse_01"             , name: "Corps Femme Unique"        , cat: "misc"      , tier: "diamond"  },
  { model: "u_f_m_miranda"               , name: "Miranda"                   , cat: "misc"      , tier: "diamond"  },
  { model: "u_f_m_promourn_01"           , name: "Endeuille Femme"           , cat: "misc"      , tier: "diamond"  },
  { model: "u_f_o_moviestar"             , name: "Star Cinema"               , cat: "misc"      , tier: "diamond"  },
  { model: "u_f_o_prolhost_01"           , name: "Host Prologue"             , cat: "misc"      , tier: "diamond"  },
  { model: "u_f_y_bikerchic"             , name: "Biker Femme"               , cat: "misc"      , tier: "diamond"  },
  { model: "u_f_y_comjane"               , name: "Jane Commune"              , cat: "misc"      , tier: "diamond"  },
  { model: "u_f_y_danceburl_01"          , name: "Danseuse Burlesque"        , cat: "misc"      , tier: "diamond"  },
  { model: "u_f_y_dancelthr_01"          , name: "Danseuse Cuir"             , cat: "misc"      , tier: "diamond"  },
  { model: "u_f_y_dancerave_01"          , name: "Danseuse Rave"             , cat: "misc"      , tier: "diamond"  },
  { model: "u_f_y_genhot_01"             , name: "Femme Sexy Unique"         , cat: "misc"      , tier: "diamond"  },
  { model: "u_f_y_hotposh_01"            , name: "Femme Chic"                , cat: "misc"      , tier: "diamond"  },
  { model: "u_f_y_jewelass_01"           , name: "Bijoutiere"                , cat: "misc"      , tier: "diamond"  },
  { model: "u_f_y_mistress"              , name: "Maitresse"                 , cat: "misc"      , tier: "diamond"  },
  { model: "u_f_y_poppymich"             , name: "Poppy Michel"              , cat: "misc"      , tier: "diamond"  },
  { model: "u_f_y_princess"              , name: "Princesse"                 , cat: "misc"      , tier: "diamond"  },
  { model: "u_f_y_spyactress"            , name: "Actrice Espion"            , cat: "misc"      , tier: "diamond"  },
  { model: "mp_m_boatstaff_01"           , name: "Equipage Bateau"           , cat: "misc"      , tier: "diamond"  },
  { model: "mp_m_claude_01"              , name: "Claude"                    , cat: "misc"      , tier: "diamond"  },
  { model: "mp_m_famdd_01"               , name: "Families DD"               , cat: "misc"      , tier: "diamond"  },
  { model: "mp_m_fibsec_01"              , name: "Securite FIB MP"           , cat: "misc"      , tier: "diamond"  },
  { model: "mp_m_forgery_01"             , name: "Faussaire"                 , cat: "misc"      , tier: "diamond"  },
  { model: "mp_m_g_vagfun_01"            , name: "Vagos Fun"                 , cat: "misc"      , tier: "diamond"  },
  { model: "mp_m_marston_01"             , name: "Marston"                   , cat: "misc"      , tier: "diamond"  },
  { model: "mp_m_niko_01"                , name: "Niko Bellic"               , cat: "misc"      , tier: "diamond"  },
  { model: "mp_m_securoguard_01"         , name: "Garde SecuroServ"          , cat: "misc"      , tier: "diamond"  },
  { model: "mp_m_shopkeep_01"            , name: "Epicier MP"                , cat: "misc"      , tier: "diamond"  },
  { model: "mp_m_waremech_01"            , name: "Mecanicien Entrepot"       , cat: "misc"      , tier: "diamond"  },
  { model: "mp_m_weapexp_01"             , name: "Expert Armes"              , cat: "misc"      , tier: "diamond"  },
  { model: "mp_m_weapwork_01"            , name: "Armurier"                  , cat: "misc"      , tier: "diamond"  },
  { model: "mp_f_bennymech_01"           , name: "Mecanicienne Benny"        , cat: "misc"      , tier: "diamond"  },
  { model: "mp_f_boatstaff_01"           , name: "Equipage Bateau F"         , cat: "misc"      , tier: "diamond"  },
  { model: "mp_f_cardesign_01"           , name: "Designer Auto F"           , cat: "misc"      , tier: "diamond"  },
  { model: "mp_f_chbar_01"               , name: "Barmaid CH"                , cat: "misc"      , tier: "diamond"  },
  { model: "mp_f_cocaine_01"             , name: "Cocainiere"                , cat: "misc"      , tier: "diamond"  },
  { model: "mp_f_counterfeit_01"         , name: "Faussaire Femme"           , cat: "misc"      , tier: "diamond"  },
  { model: "mp_f_deadhooker"             , name: "Prostituee Morte"          , cat: "misc"      , tier: "diamond"  },
  { model: "mp_f_execpa_01"              , name: "Assistante Direction"      , cat: "misc"      , tier: "diamond"  },
  { model: "mp_f_execpa_02"              , name: "Assistante Dir. 2"         , cat: "misc"      , tier: "diamond"  },
  { model: "mp_f_forgery_01"             , name: "Faussaire F"               , cat: "misc"      , tier: "diamond"  },
  { model: "mp_f_helistaff_01"           , name: "Staff Helicoptere"         , cat: "misc"      , tier: "diamond"  },
  { model: "mp_f_meth_01"                , name: "Labo Meth Femme"           , cat: "misc"      , tier: "diamond"  },
  { model: "mp_f_misty_01"               , name: "Misty"                     , cat: "misc"      , tier: "diamond"  },
  { model: "mp_f_stripperlite"           , name: "Stripteaseuse Lite"        , cat: "misc"      , tier: "diamond"  },
  { model: "mp_f_weed_01"                , name: "Weed Femme"                , cat: "misc"      , tier: "diamond"  },
  { model: "mp_m_bennymech_01"           , name: "Mecanicien Benny"          , cat: "misc"      , tier: "diamond"  },
  { model: "mp_m_cocaine_01"             , name: "Cocainier"                 , cat: "misc"      , tier: "diamond"  },
  { model: "mp_m_meth_01"                , name: "Labo Meth"                 , cat: "misc"      , tier: "diamond"  },
  { model: "mp_m_weed_01"                , name: "Weed Homme"                , cat: "misc"      , tier: "diamond"  },
  { model: "mp_s_m_armoured_01"          , name: "Blinde MP"                 , cat: "misc"      , tier: "diamond"  },
  { model: "mp_m_avongoon"               , name: "Goon Avon"                 , cat: "misc"      , tier: "diamond"  },
  { model: "mp_m_bogdangoon"             , name: "Goon Bogdan"               , cat: "misc"      , tier: "diamond"  },
  { model: "mp_m_marksman_01"            , name: "Tireur Elite MP"           , cat: "misc"      , tier: "diamond"  },
  { model: "mp_m_medic_01"               , name: "Medecin MP"                , cat: "misc"      , tier: "diamond"  },
  { model: "mp_m_prisoner_01"            , name: "Prisonnier MP"             , cat: "misc"      , tier: "diamond"  },
  { model: "csb_abigail"                 , name: "Abigail (CSB)"             , cat: "misc"      , tier: "diamond"  },
  { model: "csb_agatha"                  , name: "Agatha (CSB)"              , cat: "misc"      , tier: "diamond"  },
  { model: "csb_ballasog"                , name: "Ballas OG (CSB)"           , cat: "misc"      , tier: "diamond"  },
  { model: "csb_bryony"                  , name: "Bryony"                    , cat: "misc"      , tier: "diamond"  },
  { model: "csb_brad"                    , name: "Brad (CSB)"                , cat: "misc"      , tier: "diamond"  },
  { model: "csb_clay"                    , name: "Clay (CSB)"                , cat: "misc"      , tier: "diamond"  },
  { model: "csb_dale"                    , name: "Dale (CSB)"                , cat: "misc"      , tier: "diamond"  },
  { model: "csb_dave"                    , name: "Dave (CSB)"                , cat: "misc"      , tier: "diamond"  },
  { model: "csb_dom"                     , name: "Dom (CSB)"                 , cat: "misc"      , tier: "diamond"  },
  { model: "csb_dreyfuss"                , name: "Dreyfuss (CSB)"            , cat: "misc"      , tier: "diamond"  },
  { model: "csb_flottzinger"             , name: "Flottzinger"               , cat: "misc"      , tier: "diamond"  },
  { model: "csb_isldj_00"                , name: "DJ Iles (CSB) 1"           , cat: "misc"      , tier: "diamond"  },
  { model: "csb_isldj_01"                , name: "DJ Iles (CSB) 2"           , cat: "misc"      , tier: "diamond"  },
  { model: "csb_isldj_02"                , name: "DJ Iles (CSB) 3"           , cat: "misc"      , tier: "diamond"  },
  { model: "csb_isldj_03"                , name: "DJ Iles (CSB) 4"           , cat: "misc"      , tier: "diamond"  },
  { model: "csb_isldj_04"                , name: "DJ Iles (CSB) 5"           , cat: "misc"      , tier: "diamond"  },
  { model: "csb_janet"                   , name: "Janet (CSB)"               , cat: "misc"      , tier: "diamond"  },
  { model: "csb_maude"                   , name: "Maude (CSB)"               , cat: "misc"      , tier: "diamond"  },
  { model: "csb_money"                   , name: "Money (CSB)"               , cat: "misc"      , tier: "diamond"  },
  { model: "csb_mrsphillips"             , name: "Mme Phillips (CSB)"        , cat: "misc"      , tier: "diamond"  },
  { model: "csb_mrstornwall"             , name: "Mme Thornwall"             , cat: "misc"      , tier: "diamond"  },
  { model: "csb_nigel"                   , name: "Nigel (CSB)"               , cat: "misc"      , tier: "diamond"  },
  { model: "csb_old_man1a"               , name: "Vieil Homme (CSB)"         , cat: "misc"      , tier: "diamond"  },
  { model: "csb_old_man2"                , name: "Vieil Homme 2 (CSB)"       , cat: "misc"      , tier: "diamond"  },
  { model: "csb_omega"                   , name: "Omega (CSB)"               , cat: "misc"      , tier: "diamond"  },
  { model: "csb_oneil"                   , name: "O'Neil (CSB)"              , cat: "misc"      , tier: "diamond"  },
  { model: "csb_ortega"                  , name: "Ortega (CSB)"              , cat: "misc"      , tier: "diamond"  },
  { model: "csb_prologuedriver"          , name: "Conducteur Prologue"       , cat: "misc"      , tier: "diamond"  },
  { model: "csb_ramp_gang"               , name: "Gang Rampe (CSB)"          , cat: "misc"      , tier: "diamond"  },
  { model: "csb_ramp_hic"                , name: "Campagnard (CSB)"          , cat: "misc"      , tier: "diamond"  },
  { model: "csb_ramp_hipster"            , name: "Hipster (CSB)"             , cat: "misc"      , tier: "diamond"  },
  { model: "csb_ramp_marine"             , name: "Marine (CSB)"              , cat: "misc"      , tier: "diamond"  },
  { model: "csb_ramp_mex"                , name: "Mexicain (CSB)"            , cat: "misc"      , tier: "diamond"  },
  { model: "csb_sasquatch"               , name: "Sasquatch"                 , cat: "misc"      , tier: "diamond"  },
  { model: "csb_talmM"                   , name: "Talm M"                    , cat: "misc"      , tier: "diamond"  },
  { model: "csb_terry"                   , name: "Terry (CSB)"               , cat: "misc"      , tier: "diamond"  },
  { model: "csb_tomepsilon"              , name: "Tom Epsilon (CSB)"         , cat: "misc"      , tier: "diamond"  },
  { model: "csb_zimbor"                  , name: "Zimbor (CSB)"              , cat: "misc"      , tier: "diamond"  },
  { model: "mp_m_counterfeit_01"         , name: "Faux-Monnayeur"            , cat: "misc"      , tier: "diamond"  },
  { model: "mp_m_destroyerboss"          , name: "Boss Destroyer"            , cat: "misc"      , tier: "diamond"  },
  { model: "mp_m_freefall_01"            , name: "Chute Libre"               , cat: "misc"      , tier: "diamond"  },
];
