-- =============================================
--   PVP HUD - Server Side
-- =============================================
-- SetMaxWantedLevel est un native CLIENT uniquement — l'appeler ici plantait
-- (SCRIPT ERROR) au démarrage, à chaque connexion joueur et toutes les 30s.
-- Le retrait du wanted level est déjà géré côté client, chaque frame
-- (voir pvp_hud/client/client.lua, thread de nettoyage du monde ambiant).
